name: Update main version

run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag to use
        required: true
      major_version:
        description: The version to update
        type: choice
        options:
          - v1

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name Guillaume ROUCHON
          git config user.email qetza@users.noreply.github.com

      - name: Tag new major version
        run: git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}

      - name: Push new major version
        run: git push origin ${{ github.event.inputs.major_version }} --force